apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: tata-prometheus
  namespace: monitor
  labels:
    app.kubernetes.io/monitored_by: tata-monitor
spec:
  replicas: 3
  serviceAccountName: tata-prometheus
  ruleNamespaceSelector: {}
  ruleSelector:
    matchLabels:
      app.kubernetes.io/monitored_by: tata-monitor
  podMonitorSelector:
    matchLabels:
      app.kubernetes.io/monitored_by: tata-monitor
  probeSelector:
    matchLabels:
      app.kubernetes.io/monitored_by: tata-monitor
  ruleNamespaceSelector: {}
  ruleSelector:
    matchLabels:
      app.kubernetes.io/monitored_by: tata-monitor
  scrapeConfigNamespaceSelector: {}
  scrapeConfigSelector:
    matchLabels:
      app.kubernetes.io/monitored_by: tata-monitor
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector:
    matchLabels:
      app.kubernetes.io/monitored_by: tata-monitor
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: local-path
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 30Gi
  alerting:
    alertmanagers:
    - apiVersion: v2
      pathPrefix: /
      namespace: monitor
      name: alertmanager-operated
      port: web

---
apiVersion: v1
kind: Service
metadata:
  name: tata-prometheus
  namespace: monitor
  labels:
    prometheus: tata-prometheus
spec:
  ports:
    - name: web
      port: 9090
      targetPort: web
  selector:
    prometheus: tata-prometheus

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitor-ingress
  namespace: monitor
  annotations:
    haproxy.org/ssl-redirect: "false"
spec:
  ingressClassName: haproxy
  rules:
    - host: prometheus.service.rke2.lab
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tata-prometheus
                port:
                  name: web
